networks:
  traefik:
    external: true
    name: traefik

services:
  app:
    image: shayandrg/makhoof-insta:latest
    container_name: makhoof-insta-prod
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.makhoof-insta.rule=Host(`makhoof.chori.cyou`)"
      - "traefik.http.routers.makhoof-insta.entrypoints=https"
      - "traefik.http.routers.makhoof-insta.tls=true"
      - "traefik.http.routers.makhoof-insta.tls.certresolver=cloudflare"
      - "traefik.http.services.makhoof-insta.loadbalancer.server.port=3000"
      - "traefik.http.routers.makhoof-insta-http.rule=Host(`makhoof.chori.cyou`)"
      - "traefik.http.routers.makhoof-insta-http.entrypoints=http"
      - "traefik.http.routers.makhoof-insta-http.middlewares=makhoof-insta-redirect"
      - "traefik.http.middlewares.makhoof-insta-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.makhoof-insta-redirect.redirectscheme.permanent=true"
